### ISSUE TITLE
update site

### ISSUE THREAD

**Issue by anyaa431** [levilucio/SyVOLT#11]
Hi,

These two update sites are not found:

1. Install DSLTrans editor (plugin at https://dl.dropboxusercontent.com/u/9650993/UpdateSiteDSLTrans/site.xml)
2. Install SyVOLT editor (plugin at https://dl.dropboxusercontent.com/u/9650993/SyVoltSyntaxUpdateSite/site.xml)

Best Regards,

**Comment by clagms** [comment]
Thank you for spotting this!
This issue was caused by Dropbox having shut down all links to the public folder.
The links are up to date now.

DSLTrans editor: https://github.com/githubbrunob/DSLTransGIT/raw/master/UpdateSiteDSLTrans/site.xml

SyVolt Editor: https://github.com/clagms/SyVOLTEditor/raw/master/SyVoltSyntaxUpdateSite/site.xml
